name = "jampon"
compatibility_date = "2025-05-01"
main = "worker.ts"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "jampondb"
database_id = "f1b9e680-527b-426a-be3b-b0f2ab948f64"
